config/routes.rb
Project5::Application.routes.draw do
	

 
 resources :users
match '/signup' => 'users#new'

 match '/contact' => 'pages#contact'

 match '/about' => 'pages#about'

 match '/help' => 'pages#help'

  root :to =>  'pages#home'

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
attr_accessible :first_name, :last_name, :email, :username, :password, :password_confirmation

email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :first_name, :presence => true,
						:length => {:maximum => 50}
validates :last_name, :presence => true,
						:length => {:maximum => 50}
validates :email, :presence => true,
						:format => {:with => email_regex},
						:uniqueness => {:case_sensitive => false}

validates :username, :presence => true
validates :password, :presence => true,
						:confirmation => true,
						:length => {:within => 6..40}

before_save :encrypt_password

def has_pasword?(submitted_password)
	encrypted_password == encrypt(submitted_password)
end

def self.authenticate(email, submitted_password)
	user = find_by_email(email)
	return nil if user.nil?
	return user if user.has_password?(submitted_password)
end


private

def encrypt_password
	self.salt = make_salt if new_record?
	self.encrypted_password = encrypt(password)
end

def encrypt(string)
	secure_hash("#{salt}--#{string}") 
end

def make_salt
	secure_hash("#{Time.now.utc}--#{password}")
end

def secure_hash(string)
	Digest::SHA2.hexdigest(string)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end

  def contact
  @title = "Contact"
  end

  def about
  @title = "About"
  end
  
  def help
  @title = "Help"
  end
  
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	@title = "Sign up"
  end

  def update
  end

  def edit
  end

  def create
  end

  def destroy
  end

  def index
  end

  def show
  @user = User.find(params[:id])
  @title = @user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def title
	base_title = "Generic parties"
	if @title.nil?
		base_title
	else
		"#{base_title} | #{@title}"
	end
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><a href="http://news.railstutorial.org">News</a></li>
			<li><a href="http://railstutorial.org">Rails tutorial</a></li>
		</ul>
	</nav>	
</footer>

app/views/layouts/_header.erb
<header>
	<%= image_tag("logo.png", :alt => "sample App", :class => "round") %> 

		<nav class="round">
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Sign in", '#' %></li>
			</ul>		
		</nav>
</header>

app/views/layouts/_stylesheets.html.erb
	<!--[if It IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<%= stylesheet_link_tag    "blueprint/screen", :media => "screen" %>
	<%= stylesheet_link_tag    "blueprint/print", :media => "print" %>
	<!--[if It IE 8]> <%= stylesheet_link_tag    "blueprint/ie" %> <![endif]-->
	<%= stylesheet_link_tag    "custom", :media => "screen" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<<<<<<< HEAD
  <title><%= @title %></title>
<!--  <%= stylesheet_link_tag    "application", :media => "all" %> -->
  <%= stylesheet_link_tag    "blueprint/screen", :media => "screen" %>
  <%= stylesheet_link_tag    "blueprint/print", :media => "print" %>
  
  <%= csrf_meta_tags %>
=======
  <title><%=@title%></title>
	<%= csrf_meta_tags %>
<%= render 'layouts/stylesheets' %>
>>>>>>> filling-in-layout
</head>
<body>
	<div class="container">
	<%= render 'layouts/header' %>	
	<section class="round">
		<%= yield %>
	</section>
	<%= render 'layouts/footer' %>	
	<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
	<p> this is the About page for the 
	<a href="http://railstutorial.org/">ruby on rails tutorial</a>
	sample application.
	</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
	<p> this is the homepage for the 
	<a href="http://railstutorial.org/">ruby on rails tutorial</a>
	sample application.
	</p>

app/views/pages/help.html.erb
<h1>Help</h1>
	<p> this is the help page for the 
	<a href="http://railstutorial.org/">ruby on rails tutorial</a>
	sample application.
	</p>
<%= link_to "sign up now!", '#', :class => "signup_button round" %>

app/views/pages/home.html.erb
<h1>Home</h1>
	<p> this is the homepage for the 
	<a href="http://railstutorial.org/">ruby on rails tutorial</a>
	sample application.
	</p>
<%= link_to "sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class= "profile" summary="profile information">
<tr>
<td class = "main>
<h1>

<%= @user.first_name %> <%= @user.last_name %>
</h1>
</td>
<td clss ="sidebar round">
<strong> Name </strong> <%= @user.name %> <br />
<strong> URL </strong> <%= link_to user_path(@user), @user %>
</td>
</tr>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>